/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BusinessModelRouteImport } from './routes/business-model'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CorporateOfficeRouteImport } from './routes/corporate-office'
import { Route as EKartRouteImport } from './routes/e-kart'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as LifeAtVevraRouteImport } from './routes/life-at-vevra'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as WarehousesRouteImport } from './routes/warehouses'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessModelRoute = BusinessModelRouteImport.update({
  id: '/business-model',
  path: '/business-model',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateOfficeRoute = CorporateOfficeRouteImport.update({
  id: '/corporate-office',
  path: '/corporate-office',
  getParentRoute: () => rootRouteImport,
} as any)
const EKartRoute = EKartRouteImport.update({
  id: '/e-kart',
  path: '/e-kart',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const LifeAtVevraRoute = LifeAtVevraRouteImport.update({
  id: '/life-at-vevra',
  path: '/life-at-vevra',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehousesRoute = WarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business-model': typeof BusinessModelRoute
  '/calculator': typeof CalculatorRoute
  '/careers': typeof CareersRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/corporate-office': typeof CorporateOfficeRoute
  '/e-kart': typeof EKartRoute
  '/leadership': typeof LeadershipRoute
  '/life-at-vevra': typeof LifeAtVevraRoute
  '/testimonials': typeof TestimonialsRoute
  '/warehouses': typeof WarehousesRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/products/': typeof ProductsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business-model': typeof BusinessModelRoute
  '/calculator': typeof CalculatorRoute
  '/careers': typeof CareersRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/corporate-office': typeof CorporateOfficeRoute
  '/e-kart': typeof EKartRoute
  '/leadership': typeof LeadershipRoute
  '/life-at-vevra': typeof LifeAtVevraRoute
  '/testimonials': typeof TestimonialsRoute
  '/warehouses': typeof WarehousesRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/products': typeof ProductsIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business-model': typeof BusinessModelRoute
  '/calculator': typeof CalculatorRoute
  '/careers': typeof CareersRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/corporate-office': typeof CorporateOfficeRoute
  '/e-kart': typeof EKartRoute
  '/leadership': typeof LeadershipRoute
  '/life-at-vevra': typeof LifeAtVevraRoute
  '/testimonials': typeof TestimonialsRoute
  '/warehouses': typeof WarehousesRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/products/': typeof ProductsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/business-model'
    | '/calculator'
    | '/careers'
    | '/clients'
    | '/contact'
    | '/corporate-office'
    | '/e-kart'
    | '/leadership'
    | '/life-at-vevra'
    | '/testimonials'
    | '/warehouses'
    | '/products/$slug'
    | '/services/$slug'
    | '/products/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/business-model'
    | '/calculator'
    | '/careers'
    | '/clients'
    | '/contact'
    | '/corporate-office'
    | '/e-kart'
    | '/leadership'
    | '/life-at-vevra'
    | '/testimonials'
    | '/warehouses'
    | '/products/$slug'
    | '/services/$slug'
    | '/products'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/business-model'
    | '/calculator'
    | '/careers'
    | '/clients'
    | '/contact'
    | '/corporate-office'
    | '/e-kart'
    | '/leadership'
    | '/life-at-vevra'
    | '/testimonials'
    | '/warehouses'
    | '/products/$slug'
    | '/services/$slug'
    | '/products/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BusinessModelRoute: typeof BusinessModelRoute
  CalculatorRoute: typeof CalculatorRoute
  CareersRoute: typeof CareersRoute
  ClientsRoute: typeof ClientsRoute
  ContactRoute: typeof ContactRoute
  CorporateOfficeRoute: typeof CorporateOfficeRoute
  EKartRoute: typeof EKartRoute
  LeadershipRoute: typeof LeadershipRoute
  LifeAtVevraRoute: typeof LifeAtVevraRoute
  TestimonialsRoute: typeof TestimonialsRoute
  WarehousesRoute: typeof WarehousesRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-model': {
      id: '/business-model'
      path: '/business-model'
      fullPath: '/business-model'
      preLoaderRoute: typeof BusinessModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-office': {
      id: '/corporate-office'
      path: '/corporate-office'
      fullPath: '/corporate-office'
      preLoaderRoute: typeof CorporateOfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e-kart': {
      id: '/e-kart'
      path: '/e-kart'
      fullPath: '/e-kart'
      preLoaderRoute: typeof EKartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life-at-vevra': {
      id: '/life-at-vevra'
      path: '/life-at-vevra'
      fullPath: '/life-at-vevra'
      preLoaderRoute: typeof LifeAtVevraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouses': {
      id: '/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof WarehousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BusinessModelRoute: BusinessModelRoute,
  CalculatorRoute: CalculatorRoute,
  CareersRoute: CareersRoute,
  ClientsRoute: ClientsRoute,
  ContactRoute: ContactRoute,
  CorporateOfficeRoute: CorporateOfficeRoute,
  EKartRoute: EKartRoute,
  LeadershipRoute: LeadershipRoute,
  LifeAtVevraRoute: LifeAtVevraRoute,
  TestimonialsRoute: TestimonialsRoute,
  WarehousesRoute: WarehousesRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
